### ISSUE TITLE
OIDC auth tokens profile page is broken

### ISSUE THREAD

**Issue by ChrisMacNaughton** [CentauriSolutions/EyeDP#404]
```
Apr  8 06:14:07 login c039d5131c65[523]: I, [2022-04-08T06:14:07.511849 #12]  INFO -- : [7a810971-c2a7-4238-959e-c1c34bf12ed0] Completed 500 Internal Server Error in 30ms (ActiveRecord: 10.0ms | Allocations: 2693)
Apr  8 06:14:07 login c039d5131c65[523]: F, [2022-04-08T06:14:07.512792 #12] FATAL -- : [7a810971-c2a7-4238-959e-c1c34bf12ed0]   
Apr  8 06:14:07 login c039d5131c65[523]: [7a810971-c2a7-4238-959e-c1c34bf12ed0] ActiveRecord::StatementInvalid (PG::InvalidColumnReference: ERROR:  SELECT DISTINCT ON expressions must match initial ORDER BY expressions
Apr  8 06:14:07 login c039d5131c65[523]: LINE 1: SELECT DISTINCT ON (application_id) *, "oauth_access_tokens"...
Apr  8 06:14:07 login c039d5131c65[523]:                             ^
Apr  8 06:14:07 login c039d5131c65[523]: ):
Apr  8 06:14:07 login c039d5131c65[523]: [7a810971-c2a7-4238-959e-c1c34bf12ed0]   
Apr  8 06:14:07 login c039d5131c65[523]: [7a810971-c2a7-4238-959e-c1c34bf12ed0] app/controllers/profile/access_grants_controller.rb:48:in `map'
Apr  8 06:14:07 login c039d5131c65[523]: [7a810971-c2a7-4238-959e-c1c34bf12ed0] app/controllers/profile/access_grants_controller.rb:48:in `grants'
Apr  8 06:14:07 login c039d5131c65[523]: [7a810971-c2a7-4238-959e-c1c34bf12ed0] app/controllers/profile/access_grants_controller.rb:8:in `index'
```

**Comment by ChrisMacNaughton** [comment]
This was closed in #405
